#!/bin/sh

# Autostart
sxhkd &
fusuma &
xmodmap ~/.Xmodmap
xbindkeys
nitrogen --restore
picom &
$HOME/.config/polybar/launch.sh

# bspwm configuration
bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap           10

# Border colors
bspc config normal_border_color "#a936b0"
bspc config focused_border_color "#f0d3fe"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config ignore_ewmh_fullscreen enter

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
