#!/bin/sh

# Autostart
sxhkd &
fusuma &
picom &
xrdb ~/.Xresources
xmodmap ~/.Xmodmap
xbindkeys
nitrogen --restore
$HOME/.config/polybar/launch.sh

# bspwm configuration
bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap           10

# Border colors
bspc config normal_border_color "#006af9"
bspc config focused_border_color "#00c0f9"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# External Rules
bspc rule -a PulseAudioMixer state=floating follow=on center=on
bspc rule -a Clock state=floating follow=on center=on
bspc rule -a zoom desktop=^4 follow=on

